[package]
name = "buss-sc"
version = "0.1.0"
edition = "2021"
description = "Bussin protocol sanity checker"
license-file= "LICENSE"
repository = "https://github.com/OmentaElvis/buss-sc"

[dependencies]
clap = { version = "4.5.4", features = ["string"] }
buss-protocol = { version ="0.1.0"}
